### ISSUE TITLE
Use your Code for SoD2Reroll

### ISSUE THREAD

**Issue by Baerium** [BenjoKazooie/SoD2-Skill-Reroll#5]
Hi there,
I've spammed you with messanges about your SoD2 Reroll programm. 
In order to release an updated version of it, the Mods in the discord requires the permission from you.

Am I Allowed to use your code for non-commercial use for the SoD2 modding  community? [https://github.com/Baerium/SoD2-Reroll2]

**Comment by BenjaminNoer** [comment]
Hey, sorry for not replying. I've been very busy lately. You have my permission to update it and use it as you wish and if I need to go on the discord server just send me a link and I'll tell the mods there.

**Comment by Baerium** [comment]
Thanks! I'm going to refactor that code base now, since I know you are ok with me using your work. 
BTW: I looked through your code base - and please get to know the first "S" in the SOLID principle (https://www.digitalocean.com/community/conceptual_articles/s-o-l-i-d-the-first-five-principles-of-object-oriented-design#single-responsibility-principle). It makes testing for you and other people easier
